version: 2
updates:
  - package-ecosystem: "docker"
    schedule:
      interval: "daily"
    assignees:
      - sonicgd
  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    assignees:
      - sonicgd
