name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Base image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: sitkoru/php7:stable, sitkoru/php7:base-${{ github.run_number }}
      - name: Fpm image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          file: ./Dockerfile.FPM
          tags: sitkoru/php7:fpm, sitkoru/php7:fpm-${{ github.run_number }}
      - name: Dev image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          file: ./Dockerfile.Dev
          tags: sitkoru/php7:dev, sitkoru/php7:dev-${{ github.run_number }}
