name: Main

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [5.6.40, 7.1.33, 7.2.34, 7.3.33, 7.4.32, 8.0.24]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build fpm image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          target: fpm
      - name: Build dev image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          target: dev
      - name: Build ssh image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          target: ssh
      - name: Build nginx image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          target: with-nginx
      - name: Build nginx with ssh image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          target: with-nginx-ssh

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        uses: sitkoru/semantic-release-action@v1
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}